### ISSUE TITLE
RNAErnieTokenizer or RNATokenizer ?

### ISSUE THREAD

**Issue by haochen-MBZUAI** [CatIIIIIIII/RNAErnie2#2]
In the author's github(https://github.com/CatIIIIIIII/RNAErnie2/blob/main/rnaernie/src/models/rnaernie/tokenization_rnaernie.py), he use 'class RNAErnieTokenizer(RNATokenizer):' as his tokenizer, but in the model card of 'multimolecule/rnaernie', 'from .tokenization_utils import RNATokenizer' is appled to import the tokenizer, which one should i use, RNAErnieTokenizer or RNATokenizer ?

**Comment by CatIIIIIIII** [comment]
I think both are okay. I did not observe any functional difference. You could try a same sequence on both tokenizer, and if they are difference, pls put it here.

**Comment by haochen-MBZUAI** [comment]
> I think both are okay. I did not observe any functional difference. You could try a same sequence on both tokenizer, and if they are difference, pls put it here.

Thanks for your reply, i carefully check the tokenizer config of (https://huggingface.co/multimolecule/rnaernie), i found it is rnatokenizer (maxlength=512), while the tokenizer of ( https://huggingface.co/WANGNingroci/RNAErnie) is RNAErnietokenizer (maxlength=2048), I tried the same sequence data on different tokenzier but same checkpoint(https://huggingface.co/WANGNingroci/RNAErnie), the extracted backbone is different. If i want to extract the feature from the cDNA sequence, which one should i apply?

**Comment by CatIIIIIIII** [comment]
hi, it depends on the length distribution of your dataset. The max length means that the exceeding part of sequence that larger than the value will be discarded. Moreover, the maximum length will decide the tokenization time but it is very trivial for small dataset.
